return {
	-- "saghen/blink.cmp",
	-- lazy = false, -- lazy loading handled internally
	-- dependencies = {
	-- 	"hrsh7th/cmp-buffer", -- source for text in buffer
	-- 	"hrsh7th/cmp-path", -- source for file system paths
	-- 	"L3MON4D3/LuaSnip", -- snippet engine
	-- 	"saadparwaiz1/cmp_luasnip", -- for autocompletion
	-- 	"rafamadriz/friendly-snippets", -- useful snippets
	-- 	"onsails/lspkind.nvim", -- vs-code like pictograms
	-- 	-- "mlaursen/vim-react-snippets",
	-- },
	--
	-- version = "v0.*",
	-- opts = {
	-- 	keymap = {
	-- 		preset = "default",
	-- 		["<CR>"] = { "select_and_accept" },
	-- 	},
	--
	-- 	appearance = {
	-- 		use_nvim_cmp_as_default = true,
	-- 		nerd_font_variant = "mono",
	-- 	},
	--
	-- 	sources = {
	-- 		default = { "lsp", "path", "snippets", "buffer" },
	-- 	},
	-- },
}
